version: '3.8'

services:
  api-psgames:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: app_api
    ports:
      - "4401:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend-psgames:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "4400:80"
    restart: always
    depends_on:
      - api